const ExperiencesList = [
    {
        title: 'Frontend Developer',
        company: 'Portsis Yazılım',
        jobLocation: 'Bursa, Türkiye',
        jobType: 'Freelancer',
        workingMethods: 'Hybrid',
        startYear: 'Mayıs 2025',
        endYear: 'Halen',
    },
    {
        title: 'Grafik Tasarımcı',
        company: 'Dara Aksesuar',
        jobLocation: 'Mardin, Türkiye',
        jobType: 'Freelancer',
        workingMethods: 'Remote',
        startYear: '2017',
        endYear: 'Halen',
    },
    {
        title: 'Frontend Developer',
        company: 'Ürünver Mühendislik',
        jobLocation: 'Mersin, Türkiye',
        jobType: 'Tam Zamanlı',
        workingMethods: 'Remote',
        startYear: 'Aralık 2022',
        endYear: 'Mayıs 2023',
    },
    {
        title: 'UI Designer & Frontend Developer',
        company: 'Rihef Software & Consulting',
        jobLocation: 'İstanbul, Türkiye',
        jobType: 'Tam Zamanlı',
        workingMethods: 'Remote',
        startYear: 'Temmuz 2022',
        endYear: 'Ekim 2022',
    },
    {
        title: 'Frontend Developer',
        company: 'Phonyloops',
        jobLocation: 'İstanbul, Türkiye',
        jobType: 'Freelancer',
        workingMethods: 'Remote',
        startYear: 'Haziran 2022',
        endYear: 'Temmuz 2023',
    },
    {
        title: 'Frontend Developer',
        company: 'Clockwork Agency',
        jobLocation: 'İstanbul, Türkiye',
        jobType: 'Stajyer',
        workingMethods: 'Remote',
        startYear: 'Ocak 2022',
        endYear: 'Mayıs 2022',
    },
];

export default ExperiencesList;
